from tkinter import *
window = Tk()
window.title("Interest Calculator")
window.geometry("400x400")
Plbl = Label(text="Principal Amount: ", bg="#26FF00", height=3, width=20)
p = Entry(window)
Rlbl = Label(text="Rate of Interest: ", bg="#FF0000", height=3, width=20)
r = Entry(window)
Tlbl = Label(text="Time Period: ", bg="#00DDFF", height=3, width=20)
t = Entry(window)
simpleInterest_lbl = Label(text="Simple Interest:")
compoundInterest_lbl = Label(text="Compound Interest:")
textbox1 = Text(window, height=1, width=20)
textbox2 = Text(window, height=1, width=20)
def display():
    principal = int(p.get())
    rate = int(r.get())
    time = int(t.get())
    simpleInterest = (principal * rate * time) / 100
    compoundInterest = (principal * ((1 + rate / 100) ** time)) - principal
    textbox1.delete("1.0", END)
    textbox2.delete("1.0", END)
    textbox1.insert(END, simpleInterest)
    textbox2.insert(END, compoundInterest)
Plbl.place(x=20, y=20)
p.place(x=220, y=35)
Rlbl.place(x=20, y=80)
r.place(x=220, y=95)
Tlbl.place(x=20, y=140)
t.place(x=220, y=155)
Button(window, text="Calculate", command=display).place(x=150, y=210)
simpleInterest_lbl.place(x=20, y=260)
textbox1.place(x=180, y=260)
compoundInterest_lbl.place(x=20, y=310)
textbox2.place(x=180, y=310)
window.mainloop()